
import { Tool } from '@/types/Tool';

// This data simulates the dynamic folder structure you mentioned
// In a real implementation, this would be generated by scanning folders
export const toolsData: Tool[] = [
  {
    id: 'calculator',
    name: 'Advanced Calculator',
    description: 'A powerful calculator with scientific functions and history tracking',
    icon: '🧮',
    category: 'utilities',
    tags: ['math', 'calculator', 'scientific'],
    folder: 'calculator',
    dateAdded: '2024-01-15',
    version: '2.1.0',
    author: 'Tool Team'
  },
  {
    id: 'text-editor',
    name: 'Text Editor Pro',
    description: 'Rich text editor with syntax highlighting and auto-save functionality',
    icon: '📝',
    category: 'productivity',
    tags: ['editor', 'text', 'markdown', 'code'],
    folder: 'text-editor',
    dateAdded: '2024-01-20',
    version: '1.5.3',
    author: 'Code Guild'
  },
  {
    id: 'color-picker',
    name: 'Color Palette Generator',
    description: 'Generate beautiful color palettes for your design projects',
    icon: '🎨',
    category: 'design',
    tags: ['color', 'palette', 'design', 'hex'],
    folder: 'color-picker',
    dateAdded: '2024-01-25',
    version: '1.2.1',
    author: 'Design Studio'
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between different units of measurement with ease',
    icon: '⚖️',
    category: 'utilities',
    tags: ['conversion', 'units', 'metric', 'imperial'],
    folder: 'unit-converter',
    dateAdded: '2024-02-01',
    version: '1.0.5',
    author: 'Math Wizards'
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Create QR codes for URLs, text, and contact information',
    icon: '📱',
    category: 'utilities',
    tags: ['qr', 'code', 'generator', 'mobile'],
    folder: 'qr-generator',
    dateAdded: '2024-02-05',
    version: '1.3.0',
    author: 'Mobile Team'
  },
  {
    id: 'password-generator',
    name: 'Secure Password Generator',
    description: 'Generate strong, secure passwords with customizable options',
    icon: '🔐',
    category: 'security',
    tags: ['password', 'security', 'generator', 'encryption'],
    folder: 'password-generator',
    dateAdded: '2024-02-10',
    version: '2.0.1',
    author: 'Security Team'
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize and optimize images while maintaining quality',
    icon: '🖼️',
    category: 'media',
    tags: ['image', 'resize', 'optimize', 'compress'],
    folder: 'image-resizer',
    dateAdded: '2024-02-15',
    version: '1.4.2',
    author: 'Media Lab'
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate, and minify JSON data with syntax highlighting',
    icon: '🔧',
    category: 'development',
    tags: ['json', 'formatter', 'validator', 'developer'],
    folder: 'json-formatter',
    dateAdded: '2024-02-20',
    version: '1.1.8',
    author: 'Dev Tools'
  },
  {
    id: 'habit-tracker',
    name: 'Habit Tracker',
    description: 'Track your daily habits and build positive routines',
    icon: '✅',
    category: 'productivity',
    tags: ['habits', 'tracking', 'goals', 'routine'],
    folder: 'habit-tracker',
    dateAdded: '2024-02-25',
    version: '1.6.0',
    author: 'Wellness Team'
  },
  {
    id: 'markdown-editor',
    name: 'Markdown Editor',
    description: 'Write and preview Markdown with live rendering and export options',
    icon: '📄',
    category: 'productivity',
    tags: ['markdown', 'editor', 'preview', 'export'],
    folder: 'markdown-editor',
    dateAdded: '2024-03-01',
    version: '1.7.3',
    author: 'Content Creators'
  },
  {
    id: 'weather-widget',
    name: 'Weather Dashboard',
    description: 'Check current weather and forecasts for any location',
    icon: '🌤️',
    category: 'information',
    tags: ['weather', 'forecast', 'location', 'temperature'],
    folder: 'weather-widget',
    dateAdded: '2024-03-05',
    version: '2.2.1',
    author: 'Weather Team'
  },
  {
    id: 'expense-tracker',
    name: 'Expense Tracker',
    description: 'Track your expenses and manage your budget effectively',
    icon: '💰',
    category: 'finance',
    tags: ['expense', 'budget', 'money', 'finance'],
    folder: 'expense-tracker',
    dateAdded: '2024-03-10',
    version: '1.9.2',
    author: 'Finance Team'
  }
];

// This function simulates how you would dynamically discover tools from folders
export const discoverToolsFromFolders = (): Tool[] => {
  // In a real Next.js app, this would use fs.readdir() to scan the tools directory
  // For this demo, we return the static data above
  console.log('🔍 Discovering tools from folder structure...');
  return toolsData;
};
